### ISSUE TITLE
Doesn't work with Firefox

### ISSUE THREAD

**Issue by ziyanwan** [theyak/contextmenu#2]
It doesn't work with Firefox. I tried version 56.0.2.

**Comment by larbear** [comment]
We have used the menu successfully in Firefox. Can you create a jsfiddle or jspad showing the issue?

**Comment by ziyanwan** [comment]
https://jsfiddle.net/ja483yk9/
I debug it a little bit, and find e.target.contextMenu in display() is predefined as null in Firefox, and cannot be set to anything else. If I replace the variable name contextMenu to contextMenu1, then it works.

**Comment by larbear** [comment]
Thanks. It's been a long time since I've looked at this code, but I'll try to look at it this weekend and see if I can remember the things I did.

**Comment by theyak** [comment]
I've implemented a potential fix by renaming the property. Tested with the jsFiddle. Re-open if this doesn't solve the issue. Thanks.
