### ISSUE TITLE
Problems with Import as es6 module 

### ISSUE THREAD

**Issue by n-peugnet** [theyak/contextmenu#4]
Hello,

I am trying to import your module in my project using es6 import method, then bundled with webpack. 
```js
import ContextMenu from "./contextmenu";
```

But I get this error:
```
Uncaught TypeError: window.removeEventListener is not a function
    at closeContextMenu (contextmenu.js:413)
    at onContextMenu (contextmenu.js:220)
    at Object.display (contextmenu.js:547)
```

I noticed this comes from window variable being set as `{}`, so I tried to change the last line:
```js
} )( this );
```
into:
```js
} )( window );
```

and it worked, but I am not really sure of what are the implications of this change.
It also works with this change when I import the file from a `<script>` tag in html.

Can this be changed without breaking anything else ?

**Comment by theyak** [comment]
It's been a long time since I've looked at this, and have never included it with webpack, but it seems like a reasonable change. Let us know how it works going forward. If everything seems OK I can update the repo.
